### ISSUE TITLE
Start work on push and email notifications

### ISSUE THREAD

**Issue by naclcaleb** [highlowapp/User#4]
Pretty soon we'll be done with the backend, and start working on the frontend. One of the most important parts of the frontend is that it needs push notifications to encourage you to enter your high/low, notify you when someone likes or comments on your high/low, etc.

We also should set up email notifications just in case.

I put this in the `User` service repo because we could potentially just put `push_notify` and `email_notify` functions into the `User` class. 

However, it may be a better approach to create a whole new service called `Notifications`. 
That would help to keep the code separated.

The only hiccup is security issues. How do we make it so that only we can send notifications, and not some random technically-inclined hacker sending HTTP requests to our `Notifications` service?

Currently, I'm thinking some sort of password protection would be best, where we have a secret password that is stored in our private `config` repo along with the rest of our secret files. 

Whenever we make a request for a notification, we have to send the password with it. 

Thoughts?

**Comment by naclcaleb** [comment]
After looking at Apple's docs for push notifications, I think we need to set up a separate service.

**Comment by Redemption777** [comment]
I think we should create a separate service like the docs say.

**Comment by naclcaleb** [comment]
Alright, I guess I'll close the issue then.
